[package]
name = "embassy-mqtt"
version = "0.1.0"
edition = "2021"
license = "Apache 2.0"

[workspace]
members = [
    "buffer", "queue-vec"
]

## Workspace wide dependencies
[workspace.dependencies]
thiserror = { version = "2.0.11", default-features = false }

[dependencies]
## From Workspace
buffer = { version = "*", path = "./buffer", default-features = false, features = ["serde", "embedded"]}
queue-vec = { version = "*", default-features = false, path = "./queue-vec"}

## Other
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
defmt = { version = "0.3.10", optional = true }
heapless = "0.8.0"
embassy-time = { version = ">= 0.3.0, < 0.5.0", default-features = false, optional = true }
embassy-futures = { version = "^0.1.1", default-features = false }
thiserror = { workspace = true, default-features = false }
tracing = { version = "0.1.41", optional = true }

[dependencies.embassy-sync]
version = "0.6.2"
default-features = false

[dependencies.mqttrs]
version = "0.4"
git = "https://github.com/00imvj00/mqttrs.git"
rev = "dd9d381b401b1b7353c43b36123f1b2ea5fa80a1"
default-features = false
features = ["defmt"]

[dependencies.tokio]
version = "1.43.0"
features = ["macros", "time", "io-util", "net"]
optional = true

[features]
default = [ "std" ]
embassy = [ "dep:embassy-time" ]
std = [ "embassy-sync/std", "queue-vec/std", "dep:tokio" ]
defmt = ["dep:defmt", "embassy-sync/defmt", "embassy-time/defmt", "mqttrs/defmt", "embassy-futures/defmt", "buffer/defmt"]
tracing = [ "std", "dep:tracing" ]
test_with_broker = [ "std" ]

[dev-dependencies]

embassy-time = { version = "^0.4.0", default-features = false, features = ["std"]}
embassy-sync = { version = "0.6.2", default-features = false, features = ["std"]}

tokio = { version = "1.43.0", features = ["macros", "net", "tokio-macros", "io-util", "time", "rt-multi-thread"] }
dotenv = "0.15.0"
tracing = { version = "0.1.41" }
test-log = { version = "0.2.17", default-features = false, features = ["trace", "color"] }
ntest = "0.9.3"


