name: Test Compliance
run-name: Testing complicance for commit  ${{ github.sha }}
on: [ push, pull_request ]
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v2

