name: Test Crate
run-name: Testing commit ${{ github.sha }}
on: [ push, pull_request ]
jobs:
  test-without-broker:
    runs-on: ubuntu-latest
    services:
      mosquitto:
        image: eclipse-mosquitto:2.0
        ports:
          - 1883:1883
    env:
      MQTT_HOST: mosquitto
      MQTT_USER: test
      MQTT_PASSWORD: test-password
      MQTT_PORT: 1883
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - run: cargo test -F tracing -F test_with_broker

