name: Test Crate
run-name: Testing commit ${{ github.sha }}
on: [ push, pull_request ]
jobs:
  test-without-broker:
    runs-on: ubuntu-latest
    env:
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - run: cargo test -F tracing